name: Build and Release Artifacts

on:
  release:
    types: [published]

jobs:
  build-macos:
    runs-on: macos-15
    strategy:
      matrix:
        arch: [x86_64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get swift version
        run: swift --version

      - name: Build for macOS
        run: |
          swift build -c release --arch ${{ matrix.arch }}
          mkdir -p artifacts/macos-${{ matrix.arch }}
          cp .build/release/fishee artifacts/macos-${{ matrix.arch }}/

      - name: Upload macOS artifacts as release assets
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/macos-${{ matrix.arch }}/fishee
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get swift version
        run: swift --version

      - name: Build for Linux
        run: |
          swift build -c release
          mkdir -p artifacts/linux
          cp .build/release/fishee artifacts/linux/

      - name: Upload Linux artifacts as release assets
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/linux/fishee
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
