name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-15, ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get swift version
        run: swift --version

      - name: Run tests
        run: swift test
